-- ══════════════════════════════════════════════════════════
-- ResearchAgent: persist full context and papers to signals
-- ══════════════════════════════════════════════════════════

-- Full LLM insight generated by ResearchAgent (up to ~300 tokens)
ALTER TABLE signals ADD COLUMN IF NOT EXISTS research_context TEXT;

-- Array of {title, url} objects for the arXiv papers analyzed
ALTER TABLE signals ADD COLUMN IF NOT EXISTS research_papers JSONB;

-- Count of arXiv papers analyzed (convenience field, derivable from research_papers)
ALTER TABLE signals ADD COLUMN IF NOT EXISTS research_papers_count INT;
